spring.application.name=mercado

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JDBC URL do H2 em modo memória
spring.datasource.url=jdbc:h2:mem:meubanco
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Criação automática de tabelas (opcional)
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true
